[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
candid = "0.10.19"
ic-cdk = "0.18.7"
ic-cdk-macros = "0.18.7"
ic-stable-structures = "0.7.0"
serde = { version = "1.0", features = ["derive"] }